### PR TITLE
Add profile picture

### PR DESCRIPTION
**Pull request by waldyrious**
Add an image to be used as the bot's profile. This is related to the changes being done in the main repo, in https://github.com/tldr-pages/tldr/pull/3619.

### CODE REVIEW

**Comment by waldyrious** [comment]
Note: I took the liberty to add a yellow circle behind the bot's image, to make it more distinctive and colorful, but I'm happy to remove it if the simpler version is preferred:

| With background | No background |
|--|--|
| tldr-bot | tldr-bot (hand-tweaked) svg2 |

**Comment by agnivade** [comment]
I prefer the one without the background. Keeps it neat and clean.

**Comment by waldyrious** [comment]
Gotcha. I'll update the files tonight.

**Comment by waldyrious** [comment]
Updated :)

**Comment by Aracki** [comment]
Great one @waldyrious!

**Comment by waldyrious** [comment]
@agnivade don't forget to actually change the picture in the [bot's profile](https://github.com/tldr-bot) :)

(I'm wondering if the PNG shouldn't be higher-resolution, btw. Let me know if I should make it bigger.)

**Comment by agnivade** [comment]
I think slightly higher resolution will help.

**Comment by waldyrious** [comment]
I'll send a new PR asap (probably during the weekend).

**Pull request merged**
